CREATE DATABASE `rds-mysql-db` /*!40100 COLLATE 'utf8mb4_0900_ai_ci' */;
USE `rds-mysql-db`;

-- Create a table named 'users'
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    address VARCHAR(255),
    email VARCHAR(255)
);

-- Insert 1000 rows of random data
INSERT INTO users (name, address, email)
SELECT 
    CONCAT('Name', FLOOR(1 + (RAND() * 999))),
    CONCAT('Musterstrasse ', FLOOR(1 + (RAND() * 999)), ' , Berlin, Germany'),
    CONCAT('user', FLOOR(1 + (RAND() * 999)), '@tu-berlin.com')
FROM 
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) a,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) b,
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) c;
